CREATE TABLE JWT_tokens
(
    Id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RefreshToken TEXT            NOT NULL,
    Expires_at   TIMESTAMP       NOT NULL,
    User_id      BIGINT          NULL,
    CONSTRAINT FK_JwtTokens_Users FOREIGN KEY (User_id) REFERENCES Users (Id)
);
