<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1e5b0e48-0ff2-41c0-a94f-621c31bf57e5</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\google_auth.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\User_Date.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\JWT.proto" GrpcServices="Server" />
	  
	<Protobuf Include="Protos\user.proto" GrpcServices="Client" />
	<Protobuf Include="Protos\mail.proto" GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

	<ItemGroup>
		<None Update="Images\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</None>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="dbup-postgresql" Version="5.0.40" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.80.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.80.0" />
    <PackageReference Include="IdGen" Version="3.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.28" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Npgsql" Version="8.0.9" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.25" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

</Project>
