syntax = "proto3";

import "google/protobuf/empty.proto";

option csharp_namespace = "Auth_Service";

package test;

// The greeting service definition.
service Tester {
  // Sends a greeting
  rpc GetMessage (TestRequest) returns (TestReply);
  rpc GetMessages (google.protobuf.Empty) returns (TestReplyList);
}


message TestRequest {
  string FirstName = 1;
  string LastName = 2;
  int32 Age = 3;
}

message TestReply {
	string Message = 1;
}

message TestReplyList {
	repeated TestReply TestReplies = 1;
}