syntax = "proto3";
import "google/protobuf/empty.proto";

option csharp_namespace = "UserDate_Service";

package UserDate;

// The greeting service definition.
service UserDate {
  // Sends a greeting
  rpc GetUserId (google.protobuf.Empty) returns (UserDateResponse);
  rpc IsUserExist (UserDateResponse) returns (UserDateBoolResponse);

  rpc DeleteUser (UserDateResponse) returns (UserDateDeleteResponse);
  rpc DeleteCancel (google.protobuf.Empty) returns (UserDateDeleteResponse);
}

message UserDateResponse {
	string user_id = 1;
}

message UserDateBoolResponse {
	bool is_exist = 1;
}

message UserDateDeleteResponse {
	bool result = 1;
}

