syntax = "proto3";
import "google/protobuf/empty.proto";

option csharp_namespace = "UserDate_Service";

package UserDate;

// The greeting service definition.
service UserDate {
  // Sends a greeting
  rpc GetUserId (google.protobuf.Empty) returns (UserDateResponse);
  rpc IsUserExist (UserDateResponse) returns (UserDateBoolResponse);

  rpc DeleteUser (UserDateResponse) returns (UserDateDeleteResponse);
  rpc DeleteCancel (google.protobuf.Empty) returns (UserDateDeleteResponse);

  rpc CheckPassword (PasswordReqest) returns (UserDateBoolResponse);
  rpc ChangePassword (google.protobuf.Empty) returns (UserDateBoolResponse);
  rpc CheckChangePasswordCode (PasswordCodeReqest) returns (UserDateBoolResponse);

  rpc AddPasswordToAccount (PasswordReqest) returns (UserDateBoolResponse);
}

message UserDateResponse {
	string user_id = 1;
}

message UserDateBoolResponse {
	bool is_exist = 1;
}

message UserDateDeleteResponse {
	bool result = 1;
}

message PasswordReqest {
	int64 user_id = 1;
	string password = 2;
}

message PasswordCodeReqest {
	int64 user_id = 1;
	string code = 2;
}
