syntax = "proto3";
import "google/protobuf/empty.proto";

option csharp_namespace = "UserDate_Service";

package UserDate;

// The greeting service definition.
service UserDate {
  // Sends a greeting
  rpc GetUserId (google.protobuf.Empty) returns (UserDateResponse);
  rpc IsUserExist (UserDateResponse) returns (UserDateBoolResponse);

  rpc DeleteUser (UserDateResponse) returns (UserDateDeleteResponse);
  
  rpc CheckPassword (PasswordReqest) returns (UserDateBoolResponse);
  rpc ChangePassword (ChangePasswordReqest) returns (UserDateBoolResponse);

  rpc ChangeForgotPassword (ChangeForgotPasswordReqest) returns (OperIdResponce);
  rpc CheckChangePasswordCode (PasswordCodeReqest) returns (UserDateBoolResponse);

  rpc AddPasswordToAccount (PasswordReqest) returns (UserDateBoolResponse);
}

message UserDateResponse {
	int64 user_id = 1;
}

message UserDateBoolResponse {
	bool is_exist = 1;
}

message UserDateDeleteResponse {
	bool result = 1;
}

message PasswordReqest {
	int64 user_id = 1;
	string password = 2;
}


message ChangeForgotPasswordReqest {
	string email = 1;
}

message ChangePasswordReqest {
	int64 user_id = 1;
	string password = 2;
	string new_password = 3;
}

message OperIdResponce {
	string operId = 1;
}

message PasswordCodeReqest {
	string email = 1;
	string code = 2;
	string password = 3;
	string operId = 4;
}

